Notebook/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("note_app.urls", namespace="note_app")),
    path("", include("users.urls", namespace="users"))
]

note_app/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from . import views

"""Список сылок приложения note_app"""
app_name = "note_app"
urlpatterns = [
    path('admin/', admin.site.urls),
    path("", views.index, name= "index"),
    path("topics/", views.topics, name= "topics"),
    path("programers/", views.programers, name= "programers"),
    path("spravka/", views.spravka, name= "spravka"),
    path(r'^topics/<int:topic_id>/', views.topic, name='topic'),
    path(r"^new_topic/$", views.new_topic, name="new_topic"),
    path(r'^new_entry/<int:topic_id>/', views.new_entry, name='new_entry'),
    path(r'^edit_entry/<int:entry_id>/', views.edit_entry, name='edit_entry')
]

users/urls.py
from . import views
from django.urls import path, include
from django.contrib.auth.views import LoginView



app_name = 'users'
urlpatterns = [
    path(r'login/', LoginView.as_view(template_name='login.html'), name='login'),
    path('logout/', views.logout_view, name='logout'),
    path('register/', views.register, name='register'),
]

note_app/models.py
from django.contrib.auth.models import User
from django.db import models
# Создовай свои модули здесь


class Topic(models.Model):
    text = models.CharField(max_length = 200)
    date_added = models.DateTimeField(auto_now_add = True)
    owner = models.ForeignKey(User, on_delete=models.PROTECT)


    def __str__(self):
        return self.text


class Entry(models.Model):
    topic = models.ForeignKey("Topic", on_delete=models.PROTECT)
    text = models.TextField()
    date_added = models.DateTimeField(auto_now_add = True)


    class Meta:
        verbose_name_plural = "entries"

        def __str__(self):
           return self.text[:50] + "..."

users/models.py
from django.db import models

# Create your models here.

note_app/forms.py
from django import forms
from .models import Topic
from .models import Entry

class TopicForm(forms.ModelForm):
    class Meta:
        model = Topic
        fields = ["text"]
        labels = {"text": ""}

class EntryForm(forms.ModelForm):
    class Meta:
        model = Entry
        fields = ["text"]
        labels = {"text": ""}

note_app/views.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import render

from django.http import HttpResponseRedirect, Http404
from django.urls  import reverse

from .models import Topic,Entry
from .forms import TopicForm, EntryForm


# Create your views here.
def index(request):
    #Домашняя страница
    return render(request, "index.html")

@login_required()
def topics(request):
    """Выводит список тем"""
    topics = Topic.objects.filter(owner=request.user).order_by("date_added")
    context = {"topics":topics}
    return render(request, "topics.html", context)

@login_required()
def programers(request):
    return render(request, "programers.html")

@login_required()
def spravka(request):
    return render(request, "spravka.html")

@login_required()
def topic(request, topic_id):
    """Выводит одну тему и все её записи"""
    topic = Topic.objects.get(id=topic_id)
    if topic.owner != request.user:
        raise Http404
    entries = topic.entry_set.order_by('-date_added')
    context = {"topic": topic, 'entries':entries}
    return render(request, "topic.html", context)

@login_required()
def new_topic(request):
    if request.method != "POST":
        form = TopicForm()
    else:
        form = TopicForm(data=request.POST)
        if form.is_valid():
            new_topic = form.save(commit= False)
            new_topic.owner = request.user
            new_topic.save()
            form.save()
            return HttpResponseRedirect(reverse("note_app:topics"))
    context = {"form":form}
    return render(request, "new_topic.html", context)

@login_required()
def new_entry(request, topic_id):
    topic = Topic.objects.get(id=topic_id)
    if topic.owner != request.user:
        raise Http404
    if request.method != 'POST':
        form = EntryForm()
    else:
        form = EntryForm(data=request.POST)
        if form.is_valid():
            new_entry = form.save(commit=False)
            new_entry.topic = topic
            new_entry.save()
            return HttpResponseRedirect(reverse('note_app:topic', args= [topic_id] ))
    context = {'topic': topic, 'form': form}
    return render (request, 'new_entry.html', context)

@login_required()
def edit_entry(request, entry_id):
    entry = Entry.objects.get(id=entry_id)
    topic = entry.topic
    if topic.owner != request.user:
        raise Http404
    if request.method != 'POST':
        form = EntryForm(instance=entry)
    else:
        form = EntryForm(instance=entry, data=request.POST)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse('note_app:topic', args=[topic.id]))
    context = {'entry':entry, 'topic':topic, 'form':form}
    return render(request, 'edit_entry.html', context)

users/views.py
from django.shortcuts import render
from django.contrib.auth import authenticate, login, logout
from django.http import HttpResponseRedirect
from django.urls import reverse
from django.contrib.auth.forms import UserCreationForm
# Create your views here.
def logout_view(request):
    logout(request)
    return HttpResponseRedirect(reverse('note_app:index'))

def register(request):
    if request.method != 'POST':
        form = UserCreationForm()
    else:
        form = UserCreationForm(data=request.POST)
        if form.is_valid():
            new_user = form.save()
            auth_user = authenticate(username=new_user.username,
                                     password=request.POST['password1'])
            login(request, auth_user)
            return HttpResponseRedirect(reverse('note_app:index'))
    context = {'form':form}
    return render(request, 'register.html', context)

templates/base.html
{% load bootstrap3 %}
<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Notebook</title>

    {% bootstrap_css %}
    {% bootstrap_javascript %}
</head>

<body>
<header class="d-flex flex-wrap justify-content-center py-3 mb-4 border-bottom">
      <a href="/" class="d-flex align-items-center mb-3 mb-md-0 me-md-auto text-dark text-decoration-none">
        <svg class="bi me-2" width="40" height="32"><use xlink:href="#bootstrap"></use></svg>
      </a>

      <ul class="nav nav-pills">
          <li class="nav-item"><a href="{% url 'note_app:index'%}">Домашняя страница</a></li>
          <li class="nav-item"><a href="{% url 'note_app:topics'%}">Темы</a></li>
          <li class="nav-item">
          {% if user.is_authenticated %}
            Привет, {{user.username}}
            <a href="{% url 'users:logout' %}">Выйти</a>
          {% else %}
            <a href="{% url 'users:login' %}">Войти</a>
            <a href="{% url 'users:register' %}">Регистрация</a>
          {% endif %}
      </ul>
    </header>
    <div class="container">
        <div class="page-header">
            {% block header %}{% endblock header %}
        </div>
        <div>
            {%block content%}{% endblock content %}
        </div>
    </div>

    

<!-- <nav class="navbar navbar-default navbar-static-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle collapsed"
                        data-toggle="collapse" data-target="#navbar"
                        aria-controls="navbar">
                </button>
                <a class="navbar-brand" href="{% url 'note_app:index'%}">Книжка</a>
            </div>
            <div class="navbar-collapse collapse">
                <button type="button" class="navbar-toggle collapsed"
                        data-toggle="collapse" data-target="#navbar"
                        aria-controls="navbar">
                </button>
                <a class="nav navbar-nav" href="{% url 'note_app:topics'%}">Книжка</a>
            </div>
        </div>/.nav-collapse
    </nav>

templates/edit_entry.html
{% extends 'base.html' %}
{% block content %}
<p><a href="{% url 'note_app:topic' topic.id %}">{{topic}}</a></p>
<p>Редактирование записи:</p>
<form action="{% url 'note_app:edit_entry' entry.id %}" method="post">
      {% csrf_token %}
      {{form.as_p}}
      <button name="submit">Сохранить изменения</button>
</form>
{% endblock content %}

templates/index.html
{% extends "base.html" %}
{% block content%}
<H1>
    Наш сайт пока находится в разработке.
</H1>
{% endblock content%}

templates/login.html
{% extends 'base.html' %}
{% block content %}
{% if form.errors %}
<p>Логин или пароль неверны. Пожалуйста,попробуйте снова.</p>
{% endif %}
<form action="{% url 'users:login' %}" method="POST">
    {% csrf_token %}
    {{form.as_p}}
    <button name="submit">Войти</button>
    <input type="hidden" name="next" value="{% url 'note_app:index' %}">
</form>
{% endblock content %}

templates/new_entry.html
{% extends "base.html" %}
{% block content %}
<p>Добавить новую запись:</p>
<form action="{% url 'note_app:new_entry' topic.id %}" method="post">
    {%csrf_token%}
 {{form.as_p}}
    <button name='submit'>Добавить запись</button>
</form>
{% endblock content %}

templates/new_topic.html
{% extends "base.html"%}
{%block content%}
<H1>Добавить новую тему:</H1>
<form action="{% url 'note_app:new_topic' %}" method="post">
    {%csrf_token%}
    {{form.as_p}}
    <button name="submit">Добавить тему</button>
</form>
{% endblock content %}

templates/programers.html
{% extends "base.html" %}
{% block content%}
<p>
    Этот сайт создавался Артёмом
</p>
{% endblock content%}

templates/register.html
{% extends "base.html" %}
{% block content %}
<form method="post" action="{% url 'users:register' %}" method="POST">
    {% csrf_token %}
    {{ form.as_p }}

    <button name="submit">Регистрация</button>
    <input type="hidden" name="next" value="{% url 'note_app:index' %}">
</form>
{% endblock content %}

templates/spravka.html
{% extends "base.html" %}
{% block content%}
<p>
    Этот сайт создан для того чтобы вы
    могли записывать свои идеи
</p>
{% endblock content%}

templates/topic.html
{% extends "base.html"%}
{%block content%}
<p>
    Тема: {{topic.id}}
</p>
<p>
    Записи по теме:
</p>
<ul>
    {% for entry in entries %}
    <li>
        <p>{{entry.date_added|date:'M d, Y H:i'}}</p>
        <p>{{entry.text|linebreaks}}</p>
        <p>
            <a href="{% url 'note_app:edit_entry' entry.id %}">Редактировать запись</a>
        </p>
    </li>
    {%empty%}
    <H1>Записей по данной теме нет</H1>
    {% endfor %}
</ul>
<a href="{% url 'note_app:new_entry' topic.id %}">Добавить новую запись</a>
{% endblock content %}

templates/topics.html
{% extends "base.html"%}
{%block content%}
<p>
    Темы:
</p>
<ul>
{% for topic in topics %}
    <li>
        <a href = "{% url 'note_app:topic' topic.id %}">
            {{topic}}
        </a>
    </li>
{% endfor %}
</ul>
<a href="{% url 'note_app:new_topic' %}">Добавить новую тему</a>
{% endblock content %}